# Cấu hình cục bộ cho bài tập Servlet JDBC.
db.password=linh132435

# Cấu hình Gửi Email qua SMTP (Gmail)
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.sender.email=linhdttv0106@gmail.com
mail.sender.password=yiiclifpkezubimt